[
    {
        name: "iPhone 13",
        brand: "Apple",
        price: 1099.99,
        type: "Smartphone",
        memory: "128GB",
        processor: "A15 Bionic",
        os: "iOS 15",
        availableStocks: 50,
    },
    {
        name: "Samsung Galaxy S21",
        brand: "Samsung",
        price: 899.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Exynos 2100",
        os: "Android 11",
        availableStocks: 30,
    },
    {
        name: "Google Pixel 6",
        brand: "Google",
        price: 799.99,
        type: "Smartphone",
        memory: "128GB",
        processor: "Google Tensor",
        os: "Android 12",
        availableStocks: 20,
    },
    {
        name: "OnePlus 9",
        brand: "OnePlus",
        price: 749.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Snapdragon 888",
        os: "OxygenOS 11",
        availableStocks: 40,
    },
    {
        name: "Xiaomi Redmi Note 10",
        brand: "Xiaomi",
        price: 299.99,
        type: "Budget Smartphone",
        memory: "64GB",
        processor: "Snapdragon 678",
        os: "MIUI 12",
        availableStocks: 60,
    },
    {
        name: "Sony Xperia 5 III",
        brand: "Sony",
        price: 999.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Snapdragon 888",
        os: "Android 11",
        availableStocks: 25,
    },
    {
        name: "LG Velvet",
        brand: "LG",
        price: 699.99,
        type: "Smartphone",
        memory: "128GB",
        processor: "Snapdragon 765",
        os: "Android 10",
        availableStocks: 15,
    },
    {
        name: "Motorola Moto G Power",
        brand: "Motorola",
        price: 249.99,
        type: "Budget Smartphone",
        memory: "64GB",
        processor: "Snapdragon 662",
        os: "Android 10",
        availableStocks: 35,
    },
    {
        name: "Nokia 8.3",
        brand: "Nokia",
        price: 599.99,
        type: "Smartphone",
        memory: "128GB",
        processor: "Snapdragon 765G",
        os: "Android 10",
        availableStocks: 18,
    },
    {
        name: "Asus ROG Phone 5",
        brand: "Asus",
        price: 1299.99,
        type: "Gaming Smartphone",
        memory: "256GB",
        processor: "Snapdragon 888",
        os: "ROG UI (Android 11)",
        availableStocks: 10,
    },
    {
        name: "BlackBerry Key2",
        brand: "BlackBerry",
        price: 599.99,
        type: "QWERTY Smartphone",
        memory: "64GB",
        processor: "Snapdragon 660",
        os: "Android 8.1",
        availableStocks: 12,
    },
    {
        name: "Huawei P40 Pro",
        brand: "Huawei",
        price: 899.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Kirin 990 5G",
        os: "EMUI 10.1",
        availableStocks: 22,
    },
    {
        name: "Oppo Find X3 Pro",
        brand: "Oppo",
        price: 1199.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Snapdragon 888",
        os: "ColorOS 11.2",
        availableStocks: 28,
    },
    {
        name: "Vivo X60 Pro",
        brand: "Vivo",
        price: 799.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Exynos 1080",
        os: "Funtouch OS 11.1",
        availableStocks: 25,
    },
    {
        name: "Realme GT",
        brand: "Realme",
        price: 499.99,
        type: "Smartphone",
        memory: "128GB",
        processor: "Snapdragon 870",
        os: "Realme UI 2.0",
        availableStocks: 30,
    },
    {
        name: "ZTE Axon 30 Ultra",
        brand: "ZTE",
        price: 899.99,
        type: "Smartphone",
        memory: "256GB",
        processor: "Snapdragon 888",
        os: "MyOS (Android 11)",
        availableStocks: 15,
    },
    {
        name: "Lenovo Legion Phone Duel 2",
        brand: "Lenovo",
        price: 1099.99,
        type: "Gaming Smartphone",
        memory: "512GB",
        processor: "Snapdragon 888",
        os: "Legion OS (Android 11)",
        availableStocks: 8,
    },
    {
        name: "Alcatel 3L (2021)",
        brand: "Alcatel",
        price: 149.99,
        type: "Budget Smartphone",
        memory: "64GB",
        processor: "Mediatek MT6762",
        os: "Android 11",
        availableStocks: 45,
    },
    {
        name: "CAT S62 Pro",
        brand: "CAT",
        price: 599.99,
        type: "Rugged Smartphone",
        memory: "128GB",
        processor: "Snapdragon 660",
        os: "Android 10",
        availableStocks: 20,
    },
    {
        name: "Fairphone 4",
        brand: "Fairphone",
        price: 549.99,
        type: "Sustainable Smartphone",
        memory: "128GB",
        processor: "Snapdragon 662",
        os: "Fairphone OS (Android 11)",
        availableStocks: 15,
    },
];
